// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHZjMZ1gxTxmZTMcbGoUS7ZlQfLhzMCnw',
    appId: '1:8261982661:web:99336b33234ecd20b6d3ac',
    messagingSenderId: '8261982661',
    projectId: 'whats-app-kurs-1',
    authDomain: 'whats-app-kurs-1.firebaseapp.com',
    storageBucket: 'whats-app-kurs-1.appspot.com',
    measurementId: 'G-T5MQPEXLWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAio1iaiCBNqEMo3xv5ge8NGYaqwl4Ti3Q',
    appId: '1:8261982661:android:e56329847951f885b6d3ac',
    messagingSenderId: '8261982661',
    projectId: 'whats-app-kurs-1',
    storageBucket: 'whats-app-kurs-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALiXqKHKl642iof8tKTejFiACGJSGN484',
    appId: '1:8261982661:ios:8158e89b18e2bfa6b6d3ac',
    messagingSenderId: '8261982661',
    projectId: 'whats-app-kurs-1',
    storageBucket: 'whats-app-kurs-1.appspot.com',
    iosBundleId: 'com.example.whatsAppSebepKurs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALiXqKHKl642iof8tKTejFiACGJSGN484',
    appId: '1:8261982661:ios:06a7e16fa5653df6b6d3ac',
    messagingSenderId: '8261982661',
    projectId: 'whats-app-kurs-1',
    storageBucket: 'whats-app-kurs-1.appspot.com',
    iosBundleId: 'com.example.whatsAppSebepKurs.RunnerTests',
  );
}
